@startuml

title Reactive Agent with Reactive Reward

entity External

box "Agent"
  participant ActionInterface 
  participant RewardInterface 
end box

box "Workers"
  participant Collector
  participant Trainer
  participant Selector 
end box

alt REACTIVE
  External          -> ActionInterface : getAction( state, actions )
  ActionInterface   -> Collector : getStateActions( state, actions )
  Collector         -> Collector : getState( state )

  alt In Collector
    Collector   -> Collector : updateActionsAvailable( State, actions )
  else NOT in Collector
    Collector   -> Collector : initialiseState( state, actions )
  end

  ActionInterface    <-- Collector : State
  ActionInterface     -> Selector  : selectAction( State, actions )
  ActionInterface    <-- Selector  : action
  ActionInterface     -> Trainer   : actionSelected( State, action )
  ActionInterface    <-- Trainer
  External           <-- ActionInterface : action

  alt REACTIVE - Reward Feedback
    External          -> RewardInterface : reward( state, action, reward )
    RewardInterface   -> Collector : getStateActions( state, action )
    Collector         -> Collector : getState( state )

    alt In Collector
      Collector   -> Collector : updateActionsAvailable( State, action )
    else NOT in Collector
      Collector   -> Collector : initialiseState( state, action )
    end

    RewardInterface    <-- Collector : State
    RewardInterface     -> Trainer   : updateReward( State, action, reward )
    RewardInterface    <-- Trainer   : States
    RewardInterface     -> Collector : updateStates( States )
    External           <-- Collector
  end 
end

@enduml