@startuml

title Reactive / Active Agent Implementations

entity External
box "Agent"
  participant Interface 
  participant Collector
  participant Trainer
  participant Selector 
end box

alt HYBRID - Reactive with Active reward
  External    -> Interface : getAction( state, actions )
  Interface   -> Collector : getStateActions( state, actions )
  Collector   -> Collector : getState( state )

  alt In Collector
    Collector   -> Collector : updateActionsAvailable( State, actions )
  else NOT in Collector
    Collector   -> Collector : initialiseState( state, actions )
  end

  Interface    <-- Collector : State
  Interface     -> Selector  : selectAction( State, actions )
  Interface    <-- Selector  : action
  Interface     -> Trainer   : actionSelected( State, action )
  Interface    <-- Trainer
  External      <- Interface : getReward( state, action )
  External     --> Interface : reward
  Interface     -> Trainer   : updateReward( State, action, reward )
  Interface    <-- Trainer   : States
  Interface    ->  Collector : updateStates( States )
  External     <-- Collector 
end

@enduml